### ISSUE TITLE
Fresh install, email registration fails to create profile

### ISSUE THREAD

**Issue by crazedVic** [jeremykenedy/laravel-material-design#10]
Just wanted to make sure everything worked before I started hooking up social logins.
Register by email form actually calls the create() on Auth\RegisterController.php not the UserManagementController.php, which does create the user, and assign the role but does not setup the default profile, which then leads to a whole set of errors trying to load the bg image etc.

I suspect the correct way to fix this would be to have the email registration point to the UserManagementController instead of the RegisterController, but I leave that up to you.

**Comment by jeremykenedy** [comment]
Hi, thanks for checking out the project. The profile gets created upon account confirmation. If there’s and error please make a pr. Due to time limitations I am not actively maintaining this repo at the moment but will accept prs :)

Thabks again,
Jeremy
