### ISSUE TITLE
Dears,

### ISSUE THREAD

**Issue by Huthaifah-kholi** [jeremykenedy/laravel-material-design#14]

**Comment by Huthaifah-kholi** [comment]
Dears,
I tried to change the login process from taking email, password and replace email with the username, so this change needs to change the login controller. I search for it and open the login form: 
it appears that login form route to /login which it the same page. can anyone help me to find where the login process locate in which file?

**Comment by jeremykenedy** [comment]
The login authentication itself is handled by the laravel auth class which out the box with laravel.

**Comment by jeremykenedy** [comment]
The docs here outline how to change that to what you are seeking:

https://laravel.com/docs/5.7/authentication#included-authenticating

Under the section titled: Username Customization

Which looks like you would add the following method to the `LoginController.php` file

```
public function username()
{
    return 'username';
}
```
