### ISSUE TITLE
Unable to create configured logger

### ISSUE THREAD

**Issue by angelmartz** [jeremykenedy/laravel-material-design#16]
I get this error on laravel.log

`laravel.EMERGENCY: Unable to create configured logger. Using emergency logger.
{"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined.`

Solve: https://github.com/jeremykenedy/laravel-material-design/pull/15

**Comment by jeremykenedy** [comment]
Did you modify the laravel version by chance?

**Comment by angelmartz** [comment]
No, I didnt, I use Laravel 5.6.*

**Comment by jeremykenedy** [comment]
Thank you!
