### ISSUE TITLE
Implement MDL stepper - Features Request

### ISSUE THREAD

**Issue by odyright** [jeremykenedy/laravel-material-design#2]
this is a support request,
i want to implement MDL stepper form in the registration form.
Help! pls

**Comment by jeremykenedy** [comment]
Hi,

Go ahead and add this if you want I might include it in a pull request once I review the code. But as of this moment it is not on my road map due to limited resources. 

Thank you

**Comment by jeremykenedy** [comment]
https://ahlechandre.github.io/mdl-stepper/
