### ISSUE TITLE
Can't install !

### ISSUE THREAD

**Issue by satorc** [jeremykenedy/laravel-material-design#23]
Hi guys.
After the run "composer install", i'm get an error ....
========================================
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Compiler.php line 36:
                                      
  Please provide a valid cache path.  

=====================================
Any manipulation around are no luck . Help please.

**Comment by jeremykenedy** [comment]
If you want to you can make the change and PR, at this time I am not putting anything into this project.
